server:
  port: 8081
#配置mysql连接
spring:
  http:
    encoding:
      force: true
      enabled: true
  main:
    banner-mode: "off"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.112.22.1:3306/zzjdb?serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
    username: zhoux
    password: 123456

  mvc:
    static-path-pattern: /static/**

#配置mybatis
mybatis:
    #配置xml映射路径
    mapper-locations: classpath:mapper/*.xml
    #配置实体类的别名
    type-aliases-package: com.example.demo.entity
    configuration:
    #开启驼峰命名法
      map-underscore-to-camel-case: true

